[package]
name = "nnli"
version = "0.0.22"
edition = "2021"
description = "🔭 interactively explore `onnx` networks in your CLI."
license = "MIT"
authors = ["David Holtz <github.com/drbh>"]

[dependencies]
num-bigint = "0.4"
candle-onnx = "0.3.1"
clap = { version = "4.4.8", features = ["derive"] }
crossterm = "0.27.0"
indexmap = { version = "2.1.0", features = ["serde"] }
ratatui = { version = "0.24.0", features = ["crossterm"] }
serde = "1.0.195"
serde_derive = "1.0.195"
serde_json = "1.0.111"
